notifications:
  definitions:
    HOLD_LIST_CREATED:
      recipients:
        - ops@example.com
        - risk@example.com
      template-path: hold-list-created
      subject: "Hold list created"
      enabled: true
    HOLD_LIST_REMOVED:
      recipients:
        - ops@example.com
      template-path: hold-list-removed
      subject: "Hold list removed"
      enabled: true
